# Generated by Django 4.2.23 on 2025-11-05 05:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('is_active', models.BooleanField(default=True, help_text='Category status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier name', max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Supplier address')),
                ('is_active', models.BooleanField(default=True, help_text='Supplier status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='deliverylog',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='barcode',
            field=models.CharField(blank=True, help_text='Product barcode for scanning', max_length=100),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Product description'),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='maximum_stock',
            field=models.IntegerField(default=1000, help_text='Maximum stock level for reorder management', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='reorder_point',
            field=models.IntegerField(default=20, help_text='Stock level at which to reorder', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='reorder_quantity',
            field=models.IntegerField(default=100, help_text='Quantity to order when restocking', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='reserved_stock',
            field=models.IntegerField(default=0, help_text='Stock reserved for pending orders', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit (SKU) for inventory tracking', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Product weight in kg', max_digits=8),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text="Staff member's position", max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text="Staff member's salary", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hire_date', models.DateField(help_text='Date when the staff member was hired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Date when the salary was paid')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.staff')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payrolls',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_change', models.IntegerField(help_text='Quantity change (positive or negative)')),
                ('reason', models.CharField(choices=[('damage', 'Damage'), ('theft', 'Theft'), ('expired', 'Expired'), ('count_error', 'Count Error'), ('system_error', 'System Error'), ('other', 'Other')], help_text='Reason for adjustment', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(help_text='User who made the adjustment', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product being adjusted', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.lpgproduct')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment',
                'verbose_name_plural': 'Inventory Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lpgproduct',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('delivery', 'Delivery'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('return', 'Return'), ('damage', 'Damage/Loss'), ('audit', 'Audit Adjustment')], help_text='Type of stock movement', max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity moved (positive for in, negative for out)')),
                ('previous_stock', models.IntegerField(help_text='Stock level before movement')),
                ('new_stock', models.IntegerField(help_text='Stock level after movement')),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID (order ID, delivery ID, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this movement', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product involved in the movement', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.lpgproduct')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='core_stockm_product_86d6ad_idx'), models.Index(fields=['movement_type', '-created_at'], name='core_stockm_movemen_e27bb4_idx'), models.Index(fields=['created_at'], name='core_stockm_created_a48320_idx')],
            },
        ),
    ]
