# Generated by Django 5.2.6 on 2025-11-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cashier_cashiertransaction"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cashiertransaction",
            new_name="core_cashie_cashier_277e67_idx",
            old_name="core_cashier_cashier_7a8b9c_idx",
        ),
        migrations.RenameIndex(
            model_name="cashiertransaction",
            new_name="core_cashie_transac_1774fa_idx",
            old_name="core_cashier_transac_2f1a8b_idx",
        ),
    ]
