# Generated by Django 5.2.6 on 2025-11-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0005_rename_core_cashier_cashier_7a8b9c_idx_core_cashie_cashier_277e67_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Cashier who processed/delivered this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_orders",
                to="core.cashier",
            ),
        ),
    ]
