# Generated by Django 5.2.7 on 2025-12-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_pendingregistration"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pendingregistration",
            new_name="core_pendin_status_2239f1_idx",
            old_name="core_pending__status_idx",
        ),
        migrations.RenameIndex(
            model_name="pendingregistration",
            new_name="core_pendin_created_a17ae5_idx",
            old_name="core_pending__created_idx",
        ),
    ]
