# Generated by Django 5.2.7 on 2025-12-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_notification_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_custome_11f25a_idx',
            old_name='core_notifi_custome_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_custome_3cecb3_idx',
            old_name='core_notifi_custome_is_read_idx',
        ),
    ]
