# Generated by Django 4.2.23 on 2026-02-23 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_core_notifi_custome_idx_core_notifi_custome_11f25a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Groups multiple products in a single order together'),
        ),
    ]
