# Generated by Django 4.2.23 on 2026-02-23 07:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_batch_id_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Customer profile picture', null=True, upload_to=core.models.customer_profile_picture_path),
        ),
    ]
